from typing import Protocol


class SessionsRepository(Protocol):
    def list_sessions(self, user_id: int, limit: int, offset: int, current_refresh_token_hash: str | None = None) -> list[dict]: ...

    def count_sessions(self, user_id: int) -> int: ...

    def revoke_session(self, user_id: int, session_uid: str) -> bool: ...

    def revoke_other_sessions(self, user_id: int, current_refresh_token_hash: str | None = None) -> int: ...
