from typing import Protocol


class AssetsRepository(Protocol):
    def create_workflow(self, user_id: int, workflow_uid: str, idempotency_key: str, data: dict, steps: list[dict]) -> tuple[dict, bool]: ...

    def get_workflow(self, user_id: int, workflow_uid: str) -> dict | None: ...

    def list_workflows(self, user_id: int, status: str, limit: int, offset: int) -> list[dict]: ...

    def count_workflows(self, user_id: int, status: str) -> int: ...

    def update_workflow(self, user_id: int, workflow_uid: str, expected_version: int, values: dict) -> tuple[dict | None, bool]: ...

    def set_workflow_status(self, user_id: int, workflow_uid: str, expected_version: int, status: str) -> tuple[dict | None, bool]: ...
