PRAGMA foreign_keys = ON;

INSERT INTO learning_materials(node_slug, title, provider, material_type, url, start_url, language, is_primary, cover_label, cover_text, cover_theme, description, overview, sort_order) VALUES
('ai-literacy', 'Elements of AI · Introduction to AI', 'University of Helsinki / MinnaLearn', 'course', 'https://www.elementsofai.com/', 'https://www.elementsofai.com/', 'en', 1, 'CORE', 'AI 通识', 'g-purple', '面向非技术背景学习者的人工智能入门课程，适合建立概念、能力边界和应用场景认知。', '这份主资料从「AI 是什么」开始，逐步解释问题求解、机器学习、神经网络与社会影响。它不要求编程背景，适合作为学习路线的第一站。学完后，你应该能区分 AI、机器学习和深度学习，理解 AI 能力来自数据、模型和目标函数，而不是魔法。', 10),
('python', 'The Python Tutorial', 'Python Software Foundation', 'documentation', 'https://docs.python.org/3/tutorial/', 'https://docs.python.org/3/tutorial/introduction.html', 'en', 1, 'PY', 'Python', 'g-green', 'Python 官方教程，覆盖语法、数据结构、模块、输入输出、异常和类等基础。', '官方教程适合建立可长期使用的 Python 语法底座。它不像速成文章那样只列语法点，而是按语言能力递进组织：先写表达式和控制流，再学习数据结构、模块化、文件和异常处理。完成本节点后，你应能阅读和编写基础 Python 脚本，并为后续机器学习代码做准备。', 10),
('math-foundation', 'Mathematics for Machine Learning', 'Marc Peter Deisenroth / A. Aldo Faisal / Cheng Soon Ong', 'book', 'https://mml-book.github.io/', 'https://mml-book.github.io/book/mml-book.pdf', 'en', 1, 'MATH', '数学', 'g-yellow', '机器学习数学基础教材，聚焦线性代数、解析几何、矩阵分解、概率与优化。', '这份资料把机器学习需要的数学工具集中在一本书里，不追求覆盖所有数学分支，而是解释模型训练中最常见的线性代数、概率、优化和矩阵概念。学习目标不是做证明竞赛，而是能看懂向量、矩阵、梯度、分布和损失函数。', 10),
('machine-learning', 'Machine Learning Crash Course', 'Google for Developers', 'course', 'https://developers.google.com/machine-learning/crash-course', 'https://developers.google.com/machine-learning/crash-course', 'en', 1, 'FUND', 'ML', 'g-pink', 'Google 面向开发者的机器学习速成课程，覆盖监督学习、数据、训练与评估基础。', '这门课程适合把零散概念整理成机器学习工作流：问题定义、数据表示、模型训练、损失函数、泛化和评估。它包含短讲解和练习，适合在学完 AI 通识、Python 和基础数学后进入。', 10),
('supervised-learning', 'Supervised Learning · Machine Learning Crash Course', 'Google for Developers', 'course', 'https://developers.google.com/machine-learning/crash-course', 'https://developers.google.com/machine-learning/crash-course/linear-regression', 'en', 1, 'SUP', '监督', 'g-warm', '以线性回归、分类、特征和损失为主线理解监督学习。', '监督学习的核心是用带标签样本学习输入到输出的映射。主资料通过回归和分类任务解释标签、特征、损失、梯度下降和泛化。完成后你应能判断一个问题是否适合监督学习，并理解训练集、验证集和测试集各自的作用。', 10),
('unsupervised-learning', 'Clustering · Machine Learning Crash Course', 'Google for Developers', 'course', 'https://developers.google.com/machine-learning/clustering', 'https://developers.google.com/machine-learning/clustering/overview', 'en', 1, 'UNSUP', '无监督', 'g-yellow', 'Google 聚类课程，讲解无监督学习中的相似度、聚类流程和评估。', '无监督学习关注没有标签时如何发现结构。主资料用聚类作为入口，解释相似度、特征缩放、聚类算法和结果解释。学完后你应能把无监督学习理解为探索数据结构的工具，而不是替代监督学习的万能方法。', 10),
('training-evaluation', 'Rules of Machine Learning', 'Google for Developers', 'guide', 'https://developers.google.com/machine-learning/guides/rules-of-ml', 'https://developers.google.com/machine-learning/guides/rules-of-ml', 'en', 1, 'EVAL', '评估', 'g-warm', 'Google 的机器学习工程经验指南，聚焦上线前后的评估、特征、数据和目标设计。', '训练评估节点关注模型是否真的有用。主资料强调先建立简单基线、定义可靠指标、检查数据管道、避免训练服务偏差，并持续观察真实业务目标。它适合把模型训练从 notebook 推向工程实践前阅读。', 10),
('neural-network', 'Dive into Deep Learning · Multilayer Perceptrons', 'Dive into Deep Learning', 'book', 'https://d2l.ai/', 'https://d2l.ai/chapter_multilayer-perceptrons/index.html', 'en', 1, 'DEEP', 'NN', 'g-cyan', '开源深度学习教材，使用可运行代码解释多层感知机、反向传播和训练。', '神经网络节点从多层感知机开始理解深度学习。主资料用代码和图示解释层、激活函数、损失、反向传播、过拟合和正则化。完成后你应能把神经网络看作可组合函数，而不是黑盒术语。', 10),
('embedding', 'Embeddings Guide', 'OpenAI Platform Docs', 'documentation', 'https://platform.openai.com/docs/guides/embeddings', 'https://platform.openai.com/docs/guides/embeddings', 'en', 1, 'VEC', 'Embedding', 'g-green', 'OpenAI 官方 Embeddings 指南，解释向量表示、相似度搜索和常见应用。', 'Embedding 节点解释如何把文本、图像等内容转成可比较的向量。主资料聚焦嵌入模型的输入输出、距离度量、语义搜索、聚类和推荐。完成后你应能理解向量库、RAG 和语义检索为什么需要 Embedding。', 10),
('transformer', 'Transformers · Hugging Face NLP Course', 'Hugging Face', 'course', 'https://huggingface.co/learn/nlp-course/chapter1/4', 'https://huggingface.co/learn/nlp-course/chapter1/4', 'en', 1, 'TR', 'Transformer', 'g-cyan', 'Hugging Face NLP 课程中的 Transformer 章节，介绍架构、任务类型和 pipeline。', 'Transformer 节点建立大模型架构基础。主资料用 NLP 任务和 pipeline 解释 encoder、decoder、attention 与预训练模型如何服务分类、生成、问答等任务。完成后你应能理解为什么 Transformer 成为大语言模型的核心结构。', 10),
('llm-foundation', 'Hugging Face LLM Course', 'Hugging Face', 'course', 'https://huggingface.co/learn/llm-course/chapter1/1', 'https://huggingface.co/learn/llm-course/chapter1/1', 'en', 1, 'LLM', 'LLM', 'g-green', 'Hugging Face 大语言模型课程，覆盖 LLM 概念、token、推理、微调和应用。', 'LLM 基础节点把 Transformer 知识推进到大语言模型。主资料解释模型、tokenizer、上下文窗口、生成参数、推理限制和应用方式。完成后你应能阅读 LLM API 文档，并理解提示、上下文和模型输出之间的关系。', 10),
('fine-tuning-eval', 'Fine-tuning Guide', 'OpenAI Platform Docs', 'documentation', 'https://platform.openai.com/docs/guides/fine-tuning', 'https://platform.openai.com/docs/guides/fine-tuning', 'en', 1, 'SFT', '微调', 'g-warm', 'OpenAI 官方微调指南，解释数据准备、训练、评估和适用场景。', '微调评测节点关注什么时候需要训练，以及怎样判断训练是否值得。主资料解释微调适合稳定格式、风格或任务偏好的场景，但不适合替代知识更新。学习重点是数据质量、训练集划分、评估样例和上线前对比。', 10),
('prompt', 'Prompt Engineering Guide', 'OpenAI Platform Docs', 'documentation', 'https://platform.openai.com/docs/guides/prompt-engineering', 'https://platform.openai.com/docs/guides/prompt-engineering', 'en', 1, 'PRMT', 'Prompt', 'g-warm', 'OpenAI 官方提示工程指南，介绍清晰指令、上下文、示例和结构化输出。', 'Prompt 节点把模型能力转化为可控输出。主资料强调写清任务、提供必要上下文、拆解复杂问题、给出示例、约束输出格式。完成后你应能把模糊需求改写成稳定提示，并知道哪些问题应通过工具或 RAG 解决。', 10),
('rag', 'Build a Retrieval Augmented Generation App', 'LangChain Docs', 'tutorial', 'https://python.langchain.com/docs/tutorials/rag/', 'https://python.langchain.com/docs/tutorials/rag/', 'en', 1, 'RAG', 'RAG', 'g-yellow', 'LangChain RAG 教程，演示加载文档、切分、向量检索和生成回答。', 'RAG 节点解决模型不知道或不能直接记住的问题。主资料按工程流程讲解文档加载、文本切分、Embedding、向量检索、上下文拼接和生成。完成后你应能解释 RAG 的每个环节，以及哪些质量问题来自检索而不是模型。', 10),
('agent', 'Agents Guide', 'OpenAI Platform Docs', 'documentation', 'https://platform.openai.com/docs/guides/agents', 'https://platform.openai.com/docs/guides/agents', 'en', 1, 'AGT', 'Agent', 'g-purple', 'OpenAI Agents 指南，覆盖工具调用、任务编排、状态和安全边界。', 'Agent 节点关注模型如何规划并调用工具完成多步骤任务。主资料帮助你理解工具定义、指令、上下文、执行状态和安全控制。完成后你应能区分普通聊天、工具调用和 Agent 工作流。', 10),
('model-ops', 'Rules of Machine Learning', 'Google for Developers', 'guide', 'https://developers.google.com/machine-learning/guides/rules-of-ml', 'https://developers.google.com/machine-learning/guides/rules-of-ml', 'en', 1, 'OPS', '治理', 'g-warm', 'Google 机器学习工程规则，适合理解模型上线后的指标、数据漂移和维护策略。', '上线治理节点强调模型不是训练完就结束。主资料从工程经验出发说明监控、指标、数据质量、特征一致性、回滚和持续迭代。完成后你应能列出一个 AI 应用上线前后的基本检查清单。', 10);

INSERT INTO learning_material_sections(material_id, chapter_no, section_no, title, description, duration_minutes, source_url, sort_order) VALUES
((SELECT id FROM learning_materials WHERE node_slug='ai-literacy' AND is_primary=1), 1, 1, '什么是 AI', '区分 AI、自动化、机器学习和深度学习，建立边界感。', 35, 'https://www.elementsofai.com/', 10),
((SELECT id FROM learning_materials WHERE node_slug='ai-literacy' AND is_primary=1), 1, 2, 'AI 问题求解', '理解搜索、推理、概率和约束如何构成智能系统。', 45, 'https://www.elementsofai.com/', 20),
((SELECT id FROM learning_materials WHERE node_slug='ai-literacy' AND is_primary=1), 2, 1, '机器学习基础', '了解数据、训练、模型和泛化之间的关系。', 50, 'https://www.elementsofai.com/', 30),
((SELECT id FROM learning_materials WHERE node_slug='ai-literacy' AND is_primary=1), 2, 2, '神经网络与影响', '认识神经网络、现实应用、风险和社会影响。', 50, 'https://www.elementsofai.com/', 40),

((SELECT id FROM learning_materials WHERE node_slug='python' AND is_primary=1), 1, 1, 'Python 入门与控制流', '表达式、变量、if、for、while 和函数定义。', 45, 'https://docs.python.org/3/tutorial/introduction.html', 10),
((SELECT id FROM learning_materials WHERE node_slug='python' AND is_primary=1), 1, 2, '数据结构', '列表、元组、集合、字典和推导式。', 55, 'https://docs.python.org/3/tutorial/datastructures.html', 20),
((SELECT id FROM learning_materials WHERE node_slug='python' AND is_primary=1), 2, 1, '模块与输入输出', '模块组织、标准库、文件读写和格式化输出。', 45, 'https://docs.python.org/3/tutorial/modules.html', 30),
((SELECT id FROM learning_materials WHERE node_slug='python' AND is_primary=1), 2, 2, '错误、异常与类', '异常处理、类、迭代器和基础面向对象概念。', 55, 'https://docs.python.org/3/tutorial/errors.html', 40),

((SELECT id FROM learning_materials WHERE node_slug='math-foundation' AND is_primary=1), 1, 1, '线性代数', '向量、矩阵、线性变换和基底。', 70, 'https://mml-book.github.io/book/mml-book.pdf', 10),
((SELECT id FROM learning_materials WHERE node_slug='math-foundation' AND is_primary=1), 1, 2, '矩阵分解与向量空间', '特征值、奇异值和低维表示。', 70, 'https://mml-book.github.io/book/mml-book.pdf', 20),
((SELECT id FROM learning_materials WHERE node_slug='math-foundation' AND is_primary=1), 2, 1, '概率与分布', '随机变量、常见分布、期望和方差。', 60, 'https://mml-book.github.io/book/mml-book.pdf', 30),
((SELECT id FROM learning_materials WHERE node_slug='math-foundation' AND is_primary=1), 2, 2, '优化基础', '梯度、约束优化和机器学习中的目标函数。', 60, 'https://mml-book.github.io/book/mml-book.pdf', 40),

((SELECT id FROM learning_materials WHERE node_slug='machine-learning' AND is_primary=1), 1, 1, '机器学习问题框架', '从业务问题到标签、特征和模型目标。', 45, 'https://developers.google.com/machine-learning/crash-course', 10),
((SELECT id FROM learning_materials WHERE node_slug='machine-learning' AND is_primary=1), 1, 2, '损失、训练与梯度下降', '理解损失函数和参数更新。', 50, 'https://developers.google.com/machine-learning/crash-course/linear-regression', 20),
((SELECT id FROM learning_materials WHERE node_slug='machine-learning' AND is_primary=1), 2, 1, '泛化与数据划分', '训练集、验证集、测试集和过拟合。', 45, 'https://developers.google.com/machine-learning/crash-course/overfitting', 30),
((SELECT id FROM learning_materials WHERE node_slug='machine-learning' AND is_primary=1), 2, 2, '特征工程与评估', '数值特征、类别特征、指标和误差分析。', 50, 'https://developers.google.com/machine-learning/crash-course', 40),

((SELECT id FROM learning_materials WHERE node_slug='supervised-learning' AND is_primary=1), 1, 1, '线性回归', '用连续标签理解监督学习的基本训练过程。', 45, 'https://developers.google.com/machine-learning/crash-course/linear-regression', 10),
((SELECT id FROM learning_materials WHERE node_slug='supervised-learning' AND is_primary=1), 1, 2, '分类问题', '概率输出、阈值、准确率和混淆矩阵。', 50, 'https://developers.google.com/machine-learning/crash-course/classification', 20),
((SELECT id FROM learning_materials WHERE node_slug='supervised-learning' AND is_primary=1), 2, 1, '特征与标签质量', '识别泄漏、缺失、噪声和标签偏差。', 40, 'https://developers.google.com/machine-learning/crash-course', 30),
((SELECT id FROM learning_materials WHERE node_slug='supervised-learning' AND is_primary=1), 2, 2, '监督学习评估', '用验证集和测试集判断模型是否泛化。', 45, 'https://developers.google.com/machine-learning/crash-course', 40),

((SELECT id FROM learning_materials WHERE node_slug='unsupervised-learning' AND is_primary=1), 1, 1, '无监督学习定位', '理解没有标签时的探索式建模。', 30, 'https://developers.google.com/machine-learning/clustering/overview', 10),
((SELECT id FROM learning_materials WHERE node_slug='unsupervised-learning' AND is_primary=1), 1, 2, '相似度与特征处理', '距离、归一化和特征选择对聚类的影响。', 45, 'https://developers.google.com/machine-learning/clustering/similarity', 20),
((SELECT id FROM learning_materials WHERE node_slug='unsupervised-learning' AND is_primary=1), 2, 1, '聚类流程', '从选择算法到解释簇结果。', 45, 'https://developers.google.com/machine-learning/clustering/clustering-algorithms', 30),
((SELECT id FROM learning_materials WHERE node_slug='unsupervised-learning' AND is_primary=1), 2, 2, '评估与应用边界', '分析聚类质量、业务解释和失败场景。', 35, 'https://developers.google.com/machine-learning/clustering', 40),

((SELECT id FROM learning_materials WHERE node_slug='training-evaluation' AND is_primary=1), 1, 1, '先建立基线', '在复杂模型前先建立可解释的简单系统。', 35, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 10),
((SELECT id FROM learning_materials WHERE node_slug='training-evaluation' AND is_primary=1), 1, 2, '指标与目标', '区分代理指标、业务目标和长期质量。', 45, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 20),
((SELECT id FROM learning_materials WHERE node_slug='training-evaluation' AND is_primary=1), 2, 1, '数据管道检查', '检查数据一致性、训练服务偏差和特征漂移。', 45, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 30),
((SELECT id FROM learning_materials WHERE node_slug='training-evaluation' AND is_primary=1), 2, 2, '上线前评估', '用离线评估、在线实验和人工审查组合判断。', 45, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 40),

((SELECT id FROM learning_materials WHERE node_slug='neural-network' AND is_primary=1), 1, 1, '多层感知机', '从线性模型扩展到非线性多层网络。', 55, 'https://d2l.ai/chapter_multilayer-perceptrons/index.html', 10),
((SELECT id FROM learning_materials WHERE node_slug='neural-network' AND is_primary=1), 1, 2, '激活函数与前向传播', '理解层、激活和输出如何组合。', 50, 'https://d2l.ai/chapter_multilayer-perceptrons/mlp.html', 20),
((SELECT id FROM learning_materials WHERE node_slug='neural-network' AND is_primary=1), 2, 1, '反向传播与训练', '用梯度更新网络参数。', 60, 'https://d2l.ai/chapter_multilayer-perceptrons/backprop.html', 30),
((SELECT id FROM learning_materials WHERE node_slug='neural-network' AND is_primary=1), 2, 2, '过拟合与正则化', '用权重衰减、dropout 等方式提升泛化。', 50, 'https://d2l.ai/chapter_multilayer-perceptrons/dropout.html', 40),

((SELECT id FROM learning_materials WHERE node_slug='embedding' AND is_primary=1), 1, 1, 'Embedding 是什么', '理解向量表示和语义空间。', 25, 'https://platform.openai.com/docs/guides/embeddings', 10),
((SELECT id FROM learning_materials WHERE node_slug='embedding' AND is_primary=1), 1, 2, '生成向量', '了解文本输入、模型输出和维度。', 35, 'https://platform.openai.com/docs/guides/embeddings', 20),
((SELECT id FROM learning_materials WHERE node_slug='embedding' AND is_primary=1), 2, 1, '相似度搜索', '使用距离或相似度找到相关内容。', 40, 'https://platform.openai.com/docs/guides/embeddings', 30),
((SELECT id FROM learning_materials WHERE node_slug='embedding' AND is_primary=1), 2, 2, '应用场景', '语义搜索、聚类、推荐和 RAG 入口。', 35, 'https://platform.openai.com/docs/guides/embeddings', 40),

((SELECT id FROM learning_materials WHERE node_slug='transformer' AND is_primary=1), 1, 1, 'Transformer 概览', '了解 Transformer 解决的问题和任务类型。', 35, 'https://huggingface.co/learn/nlp-course/chapter1/4', 10),
((SELECT id FROM learning_materials WHERE node_slug='transformer' AND is_primary=1), 1, 2, 'Encoder 与 Decoder', '区分编码器、解码器和编码器-解码器模型。', 45, 'https://huggingface.co/learn/nlp-course/chapter1/4', 20),
((SELECT id FROM learning_materials WHERE node_slug='transformer' AND is_primary=1), 2, 1, 'Attention 直觉', '理解注意力如何连接上下文信息。', 50, 'https://huggingface.co/learn/nlp-course/chapter1/4', 30),
((SELECT id FROM learning_materials WHERE node_slug='transformer' AND is_primary=1), 2, 2, 'Pipeline 与任务', '用 pipeline 观察分类、生成、问答等应用。', 40, 'https://huggingface.co/learn/nlp-course/chapter1/3', 40),

((SELECT id FROM learning_materials WHERE node_slug='llm-foundation' AND is_primary=1), 1, 1, 'LLM 基本概念', '模型、参数、tokenizer 与推理。', 40, 'https://huggingface.co/learn/llm-course/chapter1/1', 10),
((SELECT id FROM learning_materials WHERE node_slug='llm-foundation' AND is_primary=1), 1, 2, 'Token 与上下文窗口', '理解输入切分、上下文长度和成本。', 45, 'https://huggingface.co/learn/llm-course/chapter1/1', 20),
((SELECT id FROM learning_materials WHERE node_slug='llm-foundation' AND is_primary=1), 2, 1, '生成参数', '温度、top-p、最大长度和输出稳定性。', 40, 'https://huggingface.co/learn/llm-course/chapter1/1', 30),
((SELECT id FROM learning_materials WHERE node_slug='llm-foundation' AND is_primary=1), 2, 2, '限制与应用方式', '识别幻觉、知识时效和工具增强需求。', 45, 'https://huggingface.co/learn/llm-course/chapter1/1', 40),

((SELECT id FROM learning_materials WHERE node_slug='fine-tuning-eval' AND is_primary=1), 1, 1, '什么时候微调', '区分提示、RAG 和微调的适用边界。', 35, 'https://platform.openai.com/docs/guides/fine-tuning', 10),
((SELECT id FROM learning_materials WHERE node_slug='fine-tuning-eval' AND is_primary=1), 1, 2, '准备训练数据', '设计高质量样例、格式和覆盖面。', 50, 'https://platform.openai.com/docs/guides/fine-tuning', 20),
((SELECT id FROM learning_materials WHERE node_slug='fine-tuning-eval' AND is_primary=1), 2, 1, '训练与验证', '划分数据、启动任务并观察训练结果。', 45, 'https://platform.openai.com/docs/guides/fine-tuning', 30),
((SELECT id FROM learning_materials WHERE node_slug='fine-tuning-eval' AND is_primary=1), 2, 2, '评估与上线', '用固定评估集和真实样例对比基础模型。', 45, 'https://platform.openai.com/docs/guides/fine-tuning', 40),

((SELECT id FROM learning_materials WHERE node_slug='prompt' AND is_primary=1), 1, 1, '清晰指令', '把任务目标、受众、边界写清楚。', 25, 'https://platform.openai.com/docs/guides/prompt-engineering', 10),
((SELECT id FROM learning_materials WHERE node_slug='prompt' AND is_primary=1), 1, 2, '上下文与示例', '提供背景、输入输出示例和反例。', 35, 'https://platform.openai.com/docs/guides/prompt-engineering', 20),
((SELECT id FROM learning_materials WHERE node_slug='prompt' AND is_primary=1), 2, 1, '拆解复杂任务', '把复杂问题分成可检查的步骤。', 35, 'https://platform.openai.com/docs/guides/prompt-engineering', 30),
((SELECT id FROM learning_materials WHERE node_slug='prompt' AND is_primary=1), 2, 2, '结构化输出', '约束格式、字段和失败兜底。', 35, 'https://platform.openai.com/docs/guides/prompt-engineering', 40),

((SELECT id FROM learning_materials WHERE node_slug='rag' AND is_primary=1), 1, 1, 'RAG 流程概览', '理解加载、切分、检索和生成的链路。', 35, 'https://python.langchain.com/docs/tutorials/rag/', 10),
((SELECT id FROM learning_materials WHERE node_slug='rag' AND is_primary=1), 1, 2, '文档加载与切分', '把原始资料变成可检索片段。', 45, 'https://python.langchain.com/docs/tutorials/rag/', 20),
((SELECT id FROM learning_materials WHERE node_slug='rag' AND is_primary=1), 2, 1, 'Embedding 与向量检索', '把问题和文档片段映射到向量空间。', 45, 'https://python.langchain.com/docs/tutorials/rag/', 30),
((SELECT id FROM learning_materials WHERE node_slug='rag' AND is_primary=1), 2, 2, '生成与引用', '把检索结果注入上下文并生成回答。', 45, 'https://python.langchain.com/docs/tutorials/rag/', 40),

((SELECT id FROM learning_materials WHERE node_slug='agent' AND is_primary=1), 1, 1, 'Agent 基本结构', '理解指令、模型、工具和运行状态。', 35, 'https://platform.openai.com/docs/guides/agents', 10),
((SELECT id FROM learning_materials WHERE node_slug='agent' AND is_primary=1), 1, 2, '工具调用', '定义工具输入输出，让模型完成外部动作。', 45, 'https://platform.openai.com/docs/guides/agents', 20),
((SELECT id FROM learning_materials WHERE node_slug='agent' AND is_primary=1), 2, 1, '多步骤任务', '管理上下文、状态和中间结果。', 45, 'https://platform.openai.com/docs/guides/agents', 30),
((SELECT id FROM learning_materials WHERE node_slug='agent' AND is_primary=1), 2, 2, '安全边界', '限制权限、校验输出并处理失败。', 40, 'https://platform.openai.com/docs/guides/agents', 40),

((SELECT id FROM learning_materials WHERE node_slug='model-ops' AND is_primary=1), 1, 1, '上线前检查', '基线、数据、指标和回滚方案。', 35, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 10),
((SELECT id FROM learning_materials WHERE node_slug='model-ops' AND is_primary=1), 1, 2, '服务与训练一致性', '检查训练服务偏差和特征管道。', 45, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 20),
((SELECT id FROM learning_materials WHERE node_slug='model-ops' AND is_primary=1), 2, 1, '监控与漂移', '观察输入分布、输出质量和业务指标。', 45, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 30),
((SELECT id FROM learning_materials WHERE node_slug='model-ops' AND is_primary=1), 2, 2, '持续迭代', '用实验、审计和反馈闭环维护系统。', 45, 'https://developers.google.com/machine-learning/guides/rules-of-ml', 40);

INSERT INTO learning_node_tags(node_slug, tag, sort_order) VALUES
('ai-literacy','入门',10),('ai-literacy','概念',20),('ai-literacy','AI 通识',30),
('python','Python',10),('python','语法',20),('python','编程基础',30),
('math-foundation','线性代数',10),('math-foundation','概率',20),('math-foundation','优化',30),
('machine-learning','机器学习',10),('machine-learning','训练',20),('machine-learning','评估',30),
('supervised-learning','监督学习',10),('supervised-learning','分类',20),('supervised-learning','回归',30),
('unsupervised-learning','无监督学习',10),('unsupervised-learning','聚类',20),('unsupervised-learning','相似度',30),
('training-evaluation','训练评估',10),('training-evaluation','指标',20),('training-evaluation','泛化',30),
('neural-network','神经网络',10),('neural-network','反向传播',20),('neural-network','深度学习',30),
('embedding','Embedding',10),('embedding','语义搜索',20),('embedding','向量库',30),
('transformer','Transformer',10),('transformer','Attention',20),('transformer','NLP',30),
('llm-foundation','LLM',10),('llm-foundation','Token',20),('llm-foundation','上下文',30),
('fine-tuning-eval','微调',10),('fine-tuning-eval','SFT',20),('fine-tuning-eval','评估',30),
('prompt','Prompt',10),('prompt','结构化输出',20),('prompt','提示工程',30),
('rag','RAG',10),('rag','检索',20),('rag','知识库',30),
('agent','Agent',10),('agent','工具调用',20),('agent','工作流',30),
('model-ops','MLOps',10),('model-ops','监控',20),('model-ops','治理',30);

INSERT INTO learning_node_links(node_slug, title, description, url, link_type, accent_color, sort_order) VALUES
('ai-literacy', 'Google AI Essentials', '面向日常工作者的 AI 应用入门资料。', 'https://grow.google/ai-essentials/', 'course', '#7C5CFF', 10),
('ai-literacy', 'Google Machine Learning Glossary', '机器学习术语速查，适合配合通识学习。', 'https://developers.google.com/machine-learning/glossary', 'reference', '#5EE0FF', 20),
('python', 'Python Standard Library', '官方标准库索引，后续查 API 使用。', 'https://docs.python.org/3/library/', 'reference', '#16A34A', 10),
('math-foundation', '3Blue1Brown Linear Algebra', '线性代数可视化视频系列。', 'https://www.3blue1brown.com/topics/linear-algebra', 'video', '#FF7AC6', 10),
('machine-learning', 'Google ML Glossary', '训练、评估和特征相关术语索引。', 'https://developers.google.com/machine-learning/glossary', 'reference', '#5EE0FF', 10),
('supervised-learning', 'Scikit-learn Supervised Learning', '监督学习算法与 API 示例。', 'https://scikit-learn.org/stable/supervised_learning.html', 'reference', '#FDBA3B', 10),
('unsupervised-learning', 'Scikit-learn Clustering', '聚类算法与示例。', 'https://scikit-learn.org/stable/modules/clustering.html', 'reference', '#FDBA3B', 10),
('training-evaluation', 'Google ML Crash Course', '配合工程规则回看训练和评估基础。', 'https://developers.google.com/machine-learning/crash-course', 'course', '#4CCBEA', 10),
('neural-network', 'Neural Networks and Deep Learning', 'Michael Nielsen 的在线书，适合理解反向传播。', 'http://neuralnetworksanddeeplearning.com/', 'book', '#EB5AAF', 10),
('embedding', 'Vector Databases Guide', '了解向量数据库在语义检索中的位置。', 'https://www.pinecone.io/learn/vector-database/', 'article', '#14B8A6', 10),
('transformer', 'The Illustrated Transformer', '用图解理解 Transformer 结构。', 'https://jalammar.github.io/illustrated-transformer/', 'article', '#C084FC', 10),
('llm-foundation', 'OpenAI Text Generation Guide', '了解大模型文本生成接口和参数。', 'https://platform.openai.com/docs/guides/text-generation', 'documentation', '#7C5CFF', 10),
('fine-tuning-eval', 'OpenAI Evals', '了解评估集和自动评测思路。', 'https://github.com/openai/evals', 'reference', '#FF8A2A', 10),
('prompt', 'OpenAI Structured Outputs', '配合提示工程学习稳定结构化返回。', 'https://platform.openai.com/docs/guides/structured-outputs', 'documentation', '#7C5CFF', 10),
('rag', 'OpenAI File Search Guide', '了解托管检索能力的另一种实现方式。', 'https://platform.openai.com/docs/guides/tools-file-search', 'documentation', '#14B8A6', 10),
('agent', 'OpenAI Function Calling Guide', '理解 Agent 工具调用的底层能力。', 'https://platform.openai.com/docs/guides/function-calling', 'documentation', '#744AEF', 10),
('model-ops', 'Google Responsible AI Practices', '补充上线治理中的安全、责任和评估视角。', 'https://ai.google/responsibility/responsible-ai-practices/', 'reference', '#EF4444', 10);

INSERT INTO learning_node_links(node_slug, title, description, url, link_type, access_type, accent_color, sort_order) VALUES
('ai-literacy', 'ShowMeAI · 人工智能知识体系', '中文 AI 入门与机器学习知识地图，适合快速建立概念框架。', 'https://www.showmeai.tech/', 'course', 'cn', '#7C5CFF', 100),
('ai-literacy', 'B站检索 · 人工智能通识入门', '国内视频资源检索入口，适合寻找通识类课程与案例讲解。', 'https://search.bilibili.com/all?keyword=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%20%E9%80%9A%E8%AF%86%20%E5%85%A5%E9%97%A8%20%E6%95%99%E7%A8%8B', 'video', 'cn', '#5EE0FF', 110),
('python', '廖雪峰 · Python 教程', '体系化中文 Python 教程，覆盖语法、函数、模块、面向对象与常用实践。', 'https://www.liaoxuefeng.com/wiki/1016959663602400', 'course', 'cn', '#16A34A', 100),
('python', 'B站检索 · 小甲鱼 Python 零基础', '适合零基础跟练的视频课程检索入口，可配合官方教程做练习。', 'https://search.bilibili.com/all?keyword=%E5%B0%8F%E7%94%B2%E9%B1%BC%20Python%20%E9%9B%B6%E5%9F%BA%E7%A1%80', 'video', 'cn', '#4ADE80', 110),
('math-foundation', 'B站检索 · 线性代数的本质', '用可视化方式补强向量、矩阵和线性变换直觉。', 'https://search.bilibili.com/all?keyword=%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0%E7%9A%84%E6%9C%AC%E8%B4%A8', 'video', 'cn', '#FDBA3B', 100),
('math-foundation', 'B站检索 · 机器学习数学基础', '围绕概率论、线性代数、微积分和优化的中文课程检索入口。', 'https://search.bilibili.com/all?keyword=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%20%E6%95%B0%E5%AD%A6%E5%9F%BA%E7%A1%80%20%E6%A6%82%E7%8E%87%E8%AE%BA%20%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0', 'video', 'cn', '#FFD56B', 110),
('machine-learning', 'ShowMeAI · 机器学习教程', '中文机器学习教程与算法图解，适合查漏补缺和复习术语。', 'https://www.showmeai.tech/', 'course', 'cn', '#4CCBEA', 100),
('machine-learning', 'B站检索 · 吴恩达机器学习中文', '经典机器学习课程的中文讲解与搬运资源检索入口。', 'https://search.bilibili.com/all?keyword=%E5%90%B4%E6%81%A9%E8%BE%BE%20%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%20%E4%B8%AD%E6%96%87', 'video', 'cn', '#5EE0FF', 110),
('supervised-learning', 'ShowMeAI · 监督学习专题', '用中文资料理解回归、分类、特征和监督学习评估。', 'https://www.showmeai.tech/', 'course', 'cn', '#FDBA3B', 100),
('supervised-learning', 'B站检索 · 监督学习 分类 回归', '按任务类型查找分类、回归和监督学习案例讲解。', 'https://search.bilibili.com/all?keyword=%E7%9B%91%E7%9D%A3%E5%AD%A6%E4%B9%A0%20%E5%88%86%E7%B1%BB%20%E5%9B%9E%E5%BD%92%20%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0', 'video', 'cn', '#FF8A2A', 110),
('unsupervised-learning', 'ShowMeAI · 聚类与降维教程', '中文算法教程入口，适合配合聚类、降维和相似度学习。', 'https://www.showmeai.tech/', 'course', 'cn', '#FDBA3B', 100),
('unsupervised-learning', 'B站检索 · 无监督学习 聚类 降维', '国内视频课程检索入口，覆盖 KMeans、PCA、降维和聚类实践。', 'https://search.bilibili.com/all?keyword=%E6%97%A0%E7%9B%91%E7%9D%A3%E5%AD%A6%E4%B9%A0%20%E8%81%9A%E7%B1%BB%20%E9%99%8D%E7%BB%B4', 'video', 'cn', '#FFD56B', 110),
('training-evaluation', 'ShowMeAI · 模型评估与指标', '中文资料入口，适合学习准确率、召回率、F1、ROC 与误差分析。', 'https://www.showmeai.tech/', 'course', 'cn', '#EF4444', 100),
('training-evaluation', 'B站检索 · 机器学习模型评估指标', '面向训练集划分、交叉验证和评估指标的视频课程检索。', 'https://search.bilibili.com/all?keyword=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%20%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0%20%E6%8C%87%E6%A0%87', 'video', 'cn', '#FF8A2A', 110),
('neural-network', '动手学深度学习 · 中文版', '开源中文深度学习教材，配套代码和章节结构完整。', 'https://zh.d2l.ai/', 'book', 'cn', '#14B8A6', 100),
('neural-network', 'B站检索 · 神经网络深度学习入门', '国内视频课程检索入口，适合理解反向传播和多层网络。', 'https://search.bilibili.com/all?keyword=%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%20%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%20%E5%85%A5%E9%97%A8', 'video', 'cn', '#5EE0FF', 110),
('embedding', '阿里云百炼 · 模型服务文档', '国内可访问的模型服务文档入口，可查中文向量与 Embedding API。', 'https://help.aliyun.com/zh/model-studio/', 'documentation', 'cn', '#14B8A6', 100),
('embedding', 'B站检索 · Embedding 向量数据库 语义搜索', '围绕向量表示、向量库和语义检索的视频教程检索入口。', 'https://search.bilibili.com/all?keyword=Embedding%20%E5%90%91%E9%87%8F%E6%95%B0%E6%8D%AE%E5%BA%93%20%E8%AF%AD%E4%B9%89%E6%90%9C%E7%B4%A2', 'video', 'cn', '#4ADE80', 110),
('transformer', 'B站检索 · 李宏毅 Transformer', '经典中文深度学习课程检索入口，适合学习 Attention 与 Transformer。', 'https://search.bilibili.com/all?keyword=%E6%9D%8E%E5%AE%8F%E6%AF%85%20Transformer', 'video', 'cn', '#C084FC', 100),
('transformer', 'B站检索 · Transformer 详解中文', '中文图解、论文精读和架构讲解的视频资源检索。', 'https://search.bilibili.com/all?keyword=Transformer%20%E8%AF%A6%E8%A7%A3%20%E4%B8%AD%E6%96%87', 'video', 'cn', '#5EE0FF', 110),
('llm-foundation', 'ModelScope · 文档中心', '国内模型社区文档入口，适合了解模型、推理、部署和应用。', 'https://modelscope.cn/docs', 'documentation', 'cn', '#7C5CFF', 100),
('llm-foundation', 'B站检索 · 大语言模型 LLM 入门', '中文 LLM 基础课程和讲座检索入口，适合理解 token、上下文和推理。', 'https://search.bilibili.com/all?keyword=%E5%A4%A7%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B%20LLM%20%E5%85%A5%E9%97%A8', 'video', 'cn', '#14B8A6', 110),
('fine-tuning-eval', '阿里云百炼 · 模型调优文档', '国内平台文档入口，适合了解微调、数据准备和评估流程。', 'https://help.aliyun.com/zh/model-studio/', 'documentation', 'cn', '#FF8A2A', 100),
('fine-tuning-eval', 'B站检索 · LoRA SFT 大模型微调', '围绕 SFT、LoRA、QLoRA 和评估实践的视频教程检索入口。', 'https://search.bilibili.com/all?keyword=LoRA%20SFT%20%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83', 'video', 'cn', '#EF4444', 110),
('prompt', '阿里云百炼 · Prompt 与模型调用文档', '国内可访问的平台文档入口，适合学习提示、参数和结构化调用。', 'https://help.aliyun.com/zh/model-studio/', 'documentation', 'cn', '#7C5CFF', 100),
('prompt', 'B站检索 · 吴恩达 Prompt Engineering 中文', '经典提示工程课程的中文讲解与搬运资源检索入口。', 'https://search.bilibili.com/all?keyword=%E5%90%B4%E6%81%A9%E8%BE%BE%20Prompt%20Engineering%20%E4%B8%AD%E6%96%87', 'video', 'cn', '#FF7AC6', 110),
('rag', '阿里云百炼 · 知识库与 RAG 文档', '国内平台文档入口，适合学习知识库、检索增强和应用搭建。', 'https://help.aliyun.com/zh/model-studio/', 'documentation', 'cn', '#14B8A6', 100),
('rag', 'B站检索 · RAG 知识库搭建', '围绕文档切分、向量检索、知识库和问答系统的视频教程检索。', 'https://search.bilibili.com/all?keyword=RAG%20%E7%9F%A5%E8%AF%86%E5%BA%93%20%E6%90%AD%E5%BB%BA', 'video', 'cn', '#FDBA3B', 110),
('agent', 'ModelScope · 文档中心', '国内模型社区文档入口，可配合学习工具调用、应用编排和 Agent 实践。', 'https://modelscope.cn/docs', 'documentation', 'cn', '#744AEF', 100),
('agent', 'B站检索 · AI Agent 工作流教程', '国内视频资源检索入口，适合学习 Agent、工具调用和工作流编排。', 'https://search.bilibili.com/all?keyword=AI%20Agent%20%E5%B7%A5%E4%BD%9C%E6%B5%81%20%E6%95%99%E7%A8%8B', 'video', 'cn', '#C084FC', 110),
('model-ops', '阿里云 PAI · 文档中心', '国内机器学习平台文档入口，适合学习训练、部署、监控和治理。', 'https://help.aliyun.com/zh/pai/', 'documentation', 'cn', '#EF4444', 100),
('model-ops', 'B站检索 · MLOps 模型部署监控', '围绕模型部署、监控、漂移和持续迭代的视频课程检索。', 'https://search.bilibili.com/all?keyword=MLOps%20%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2%20%E7%9B%91%E6%8E%A7', 'video', 'cn', '#FF8A2A', 110);

INSERT INTO learning_node_links(node_slug, title, description, url, link_type, access_type, accent_color, sort_order) VALUES
('ai-literacy', '吴恩达 · AI for Everyone 中英字幕', '吴恩达面向非技术人群的 AI 通识课，适合理解 AI 能做什么、不能做什么。', 'https://www.bilibili.com/video/BV1yC4y127uj/', 'video', 'cn', '#7C5CFF', 200),
('ai-literacy', 'DeepLearning.AI · AI For Everyone', '吴恩达原版课程页，适合补充英文术语和完整课程结构。', 'https://www.deeplearning.ai/courses/ai-for-everyone/', 'course', 'external', '#744AEF', 210),
('python', '小甲鱼 · 零基础入门学习 Python', 'B站经典 Python 入门课，适合零基础跟练语法、函数、模块和基础项目。', 'https://www.bilibili.com/video/BV1xs411Q799/', 'video', 'cn', '#16A34A', 200),
('python', '黑马程序员 · Python 零基础全套教程', '更偏就业和工程实践的体系课，适合作为基础语法后的强化训练。', 'https://www.bilibili.com/video/BV1qW4y1a7fU/', 'video', 'cn', '#4ADE80', 210),
('python', '菜鸟教程 · Python3 教程', '中文速查型教程，适合配合视频课查语法点和示例。', 'https://www.runoob.com/python3/python3-tutorial.html', 'course', 'cn', '#10B981', 220),
('math-foundation', '3Blue1Brown 官方双语 · 线性代数的本质', '用动画建立向量、矩阵、特征值和线性变换直觉，是数学基础的高质量视频补充。', 'https://www.bilibili.com/video/BV1ys411472E/', 'video', 'cn', '#FDBA3B', 200),
('math-foundation', '3Blue1Brown · Linear Algebra', '原版线性代数可视化系列，适合补充英文术语和原始讲解。', 'https://www.3blue1brown.com/topics/linear-algebra', 'video', 'external', '#FF7AC6', 210),
('machine-learning', '吴恩达 · 机器学习经典名课', '机器学习入门标杆课程，覆盖监督学习、无监督学习、损失函数和基础优化。', 'https://www.bilibili.com/video/BV164411S78V/', 'video', 'cn', '#5EE0FF', 200),
('machine-learning', '李宏毅 · 2025 机器学习', '李宏毅老师已授权转载版本，围绕现代机器学习和大模型应用展开。', 'https://www.bilibili.com/video/BV1aiADewEBC/', 'video', 'cn', '#7C5CFF', 210),
('machine-learning', 'Coursera · Machine Learning Specialization', '吴恩达新版机器学习专项课程原版入口，适合系统补全作业和英文资料。', 'https://www.coursera.org/specializations/machine-learning-introduction', 'course', 'external', '#2563EB', 220),
('supervised-learning', '吴恩达机器学习 · 监督学习章节', '通过线性回归、逻辑回归和分类任务建立监督学习基本框架。', 'https://www.bilibili.com/video/BV164411S78V/', 'video', 'cn', '#FDBA3B', 200),
('supervised-learning', '李宏毅机器学习 · 分类与回归基础', '从任务、模型、损失和泛化角度理解监督学习。', 'https://www.bilibili.com/video/BV1aiADewEBC/', 'video', 'cn', '#FF8A2A', 210),
('unsupervised-learning', '吴恩达机器学习 · 无监督学习章节', '经典课程中的聚类、降维和异常检测内容，适合作为无监督学习入门。', 'https://www.bilibili.com/video/BV164411S78V/', 'video', 'cn', '#FDBA3B', 200),
('unsupervised-learning', 'Scikit-learn · Clustering', '配合视频学习聚类 API、算法差异和实验示例。', 'https://scikit-learn.org/stable/modules/clustering.html', 'documentation', 'external', '#F59E0B', 210),
('training-evaluation', '吴恩达 · 机器学习工程生产实践 MLOps', '覆盖数据管道、模型部署、日志、追踪和监控，适合训练评估到上线的过渡学习。', 'https://www.bilibili.com/video/BV1pi4y167g5/', 'video', 'cn', '#EF4444', 200),
('training-evaluation', 'Google Cloud · MLOps 持续交付与自动化流水线', '中文架构文档，帮助理解训练、测试、发布、部署和监控的工程闭环。', 'https://docs.cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning?hl=zh-cn', 'guide', 'external', '#4CCBEA', 210),
('neural-network', '李沐 · 动手学深度学习 V2', '原作者视频课程，适合用代码理解线性回归、MLP、反向传播和 PyTorch 基础。', 'https://www.bilibili.com/video/BV1if4y147hS/', 'video', 'cn', '#14B8A6', 200),
('neural-network', '李沐 · 深度学习介绍', '从问题背景、模型能力和学习路线解释深度学习，适合进入神经网络前观看。', 'https://www.bilibili.com/video/BV1J54y187f9/', 'video', 'cn', '#5EE0FF', 210),
('embedding', '吴恩达 · Vector Databases from Embeddings to Applications', '从 Embedding 到向量数据库应用的专项课搬运，适合理解语义检索与应用链路。', 'https://www.bilibili.com/video/BV14u4y1A7fB/', 'video', 'cn', '#14B8A6', 200),
('embedding', 'ZOMI酱 · Vector 与 Embedding 关系', '中文短课解释向量数据库、Embedding 和大模型应用中的检索关系。', 'https://www.bilibili.com/video/BV1JF4m177Wd/', 'video', 'cn', '#10B981', 210),
('embedding', '阿里云百炼 · 向量化 Embedding', '国内平台文档，直接说明文本、多模态向量化和常见下游任务。', 'https://help.aliyun.com/zh/model-studio/embedding', 'documentation', 'cn', '#4ADE80', 220),
('transformer', '李沐 · Transformer 论文逐段精读', '高质量论文精读视频，适合从 Attention Is All You Need 原文理解架构细节。', 'https://www.bilibili.com/video/BV1pu411o7BE/', 'video', 'cn', '#C084FC', 200),
('transformer', '李宏毅 · 机器学习深度学习系列', '课程中覆盖深度学习、注意力机制、Transformer 和现代模型思路。', 'https://www.bilibili.com/video/BV1TAtwzTE1S/', 'video', 'cn', '#7C5CFF', 210),
('llm-foundation', '中国人民大学赵鑫团队 · 大语言模型课程', '围绕《大语言模型》书籍展开，覆盖预训练、微调、对齐、使用和评测。', 'https://www.bilibili.com/video/BV1GaRKYmEsD/', 'video', 'cn', '#7C5CFF', 200),
('llm-foundation', 'Datawhale · 大模型学习路线分享', '国内开源学习社区的大模型学习路线，适合建立 LLM 学习地图。', 'https://www.bilibili.com/video/BV1jZ421x7Sb/', 'video', 'cn', '#14B8A6', 210),
('fine-tuning-eval', '人大赵鑫团队 · 大模型微调与评测', '系统课程中包含微调、对齐和评测内容，适合建立 SFT 与评估全流程认知。', 'https://www.bilibili.com/video/BV1GaRKYmEsD/', 'video', 'cn', '#FF8A2A', 200),
('fine-tuning-eval', '阿里云百炼 · 模型调优文档', '国内平台文档入口，适合查模型调优、数据准备和调用限制。', 'https://help.aliyun.com/zh/model-studio/', 'documentation', 'cn', '#EF4444', 210),
('prompt', 'DeepLearning.AI · ChatGPT Prompt Engineering for Developers', '吴恩达与 Isa Fulford 的提示工程短课原版入口，适合系统学习指令、示例和迭代。', 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/', 'course', 'external', '#7C5CFF', 200),
('prompt', '阿里云百炼 · Prompt 与模型调用实践', '国内文档入口，适合把提示工程与国产模型调用、参数和结构化输出结合。', 'https://help.aliyun.com/zh/model-studio/', 'documentation', 'cn', '#FF7AC6', 210),
('rag', '吴恩达 · 大模型 RAG 教程', 'DeepLearning.AI RAG 课程搬运，覆盖检索增强生成的核心流程和代码思路。', 'https://www.bilibili.com/video/BV1QRbnzTEyK/', 'video', 'cn', '#FDBA3B', 200),
('rag', '从 0 到 1 精通 RAG', '较完整的中文 RAG 实战课程，包含 Embedding、向量数据库、分块和企业级问答项目。', 'https://www.bilibili.com/video/BV1ZqnyztEoq/', 'video', 'cn', '#14B8A6', 210),
('rag', '阿里云百炼 · 知识库 RAG', '国内平台文档，解释知识库如何基于 RAG 为大模型补充私有数据。', 'https://www.alibabacloud.com/help/zh/model-studio/rag-knowledge-base', 'documentation', 'cn', '#F59E0B', 220),
('agent', '吴恩达 · Agentic AI 智能体教程', '吴恩达 Agentic AI 课程搬运，覆盖反射、工具使用、规划和多智能体工作流。', 'https://www.bilibili.com/video/BV1aaxyz8ELY/', 'video', 'cn', '#744AEF', 200),
('agent', '吴恩达 · Agent 智能体教程', '更完整的 Agentic AI 系列入口，适合按模块学习工作流和评估。', 'https://www.bilibili.com/video/BV1DfrdByE2H/', 'video', 'cn', '#C084FC', 210),
('model-ops', '吴恩达 · 机器学习工程生产实践', 'MLOps 视频课，覆盖生产数据管道、模型部署、监控和追踪。', 'https://www.bilibili.com/video/BV1pi4y167g5/', 'video', 'cn', '#EF4444', 200),
('model-ops', '吴恩达 · 面向制造的机器学习工程', '从实际生产场景理解数据、模型、部署和运维流程。', 'https://www.bilibili.com/video/BV1aa411Y7Qp/', 'video', 'cn', '#FF8A2A', 210),
('model-ops', '阿里云 PAI · 模型在线部署', '国内云平台文档，适合学习模型在线服务、部署参数和 EAS 推理服务。', 'https://help.aliyun.com/zh/pai/model-deployment', 'documentation', 'cn', '#DC2626', 220);

INSERT INTO learning_node_links(node_slug, title, description, url, link_type, access_type, accent_color, sort_order) VALUES
('prompt', '吴恩达 · ChatGPT Prompt Engineering 中文', '吴恩达提示工程短课的 B 站直达版本，适合系统学习提示迭代、摘要、推理和聊天机器人。', 'https://www.bilibili.com/video/BV1e8411o7NP/', 'video', 'cn', '#FF7AC6', 220),
('prompt', 'Prompt Engineering Guide · 中文版', '开源提示工程指南中文版，适合查阅常见 prompting 技术、论文和应用模式。', 'https://www.promptingguide.ai/zh', 'guide', 'cn', '#7C5CFF', 230);
