server {
    listen 80;
    listen [::]:80;
    server_name starchart-ai.xyz www.starchart-ai.xyz;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        add_header Retry-After 3600 always;
        return 503;
    }
}
