from typing import Protocol


class AuthenticationRepository(Protocol):
    def is_username_available(self, username: str) -> bool: ...

    def register_user(self, item: dict) -> dict: ...

    def has_current_privacy_consent(self, user_id: int, policy_version: str) -> bool: ...

    def find_login_user(self, identifier: str) -> dict | None: ...

    def rehash_password(self, user_id: int, password_hash: str) -> None: ...

    def record_login(self, user_id: int | None, identifier: str, ok: bool, failure_reason: str | None, ip_address: str, user_agent: str) -> None: ...

    def increment_failed_attempts(self, user_id: int, max_attempts: int, locked_until: str) -> None: ...

    def mark_login_success(self, user_id: int, ip_address: str) -> None: ...

    def create_session(self, item: dict) -> None: ...

    def get_current_user_by_uid(self, user_uid: str) -> dict | None: ...

    def get_token_version(self, user_id: int) -> int: ...

    def find_refresh_session(self, refresh_token_hash: str) -> dict | None: ...

    def find_any_refresh_session(self, refresh_token_hash: str) -> dict | None: ...

    def touch_session(self, session_id: int, ip_address: str, user_agent: str) -> None: ...

    def rotate_refresh_session(self, session_id: int, item: dict) -> None: ...

    def revoke_token_family(self, user_id: int, token_family_uid: str, reason: str) -> None: ...

    def revoke_refresh_token(self, user_id: int, refresh_token_hash: str) -> None: ...

    def create_password_recovery(
        self,
        identifier: str,
        token_uid: str,
        token_hash: str,
        expires_at: str,
    ) -> dict | None: ...

    def cancel_password_recovery(self, token_hash: str) -> None: ...

    def confirm_security_reset(self, reset_token_hash: str, password_hash: str) -> dict | None: ...
