from typing import Protocol


class PrivacyRepository(Protocol):
    def verify_current_password(self, user_id: int, password: str) -> bool: ...

    def list_current_consents(self, user_id: int) -> list[dict]: ...

    def append_consent(self, event_uid: str, user_id: int, consent_type: str, policy_version: str, action: str, source: str) -> dict: ...

    def create_export_request(self, request_uid: str, user_id: int) -> dict: ...

    def export_user_data(self, user_id: int) -> dict: ...

    def current_deletion_request(self, user_id: int) -> dict | None: ...

    def create_deletion_request(self, request_uid: str, user_id: int, reason_code: str, scheduled_for: str) -> dict: ...

    def cancel_deletion_request(self, user_id: int, request_uid: str) -> dict | None: ...

    def execute_deletion_request(self, request_uid: str, now: str, retention_until: str) -> dict | None: ...

    def restore_deletion_request(self, request_uid: str, now: str) -> dict | None: ...

    def anonymize_deletion_request(self, request_uid: str, now: str) -> dict | None: ...
