from typing import Protocol


class AccountRepository(Protocol):
    def get_account(self, user_id: int) -> dict | None: ...

    def is_username_available(self, username: str, exclude_user_id: int | None = None) -> bool: ...

    def is_email_available(self, email: str, exclude_user_id: int | None = None) -> bool: ...

    def is_phone_available(self, phone: str, exclude_user_id: int | None = None) -> bool: ...

    def get_password_hash(self, user_id: int) -> str | None: ...

    def update_account(self, user_id: int, username: str, email: str | None, phone: str | None) -> dict: ...
