from typing import Any, Protocol


class LearningRepository(Protocol):
    def roadmap(self) -> dict[str, Any]: ...

    def resources(self, domain: str | None = None) -> list[dict[str, Any]]: ...

    def node_bundle(self, slug: str) -> dict[str, Any] | None: ...

    def node_relations(self, slug: str) -> dict[str, list[dict[str, Any]]]: ...

    def search(self, query: str, limit: int) -> list[dict[str, Any]]: ...

    def next_node(self, slug: str) -> dict[str, Any] | None: ...

    def resolve_reference(self, target_type: str, target_key: str) -> dict[str, Any] | None: ...
